# Duplicity backup configuration file

# Duplicity backup script-shell
# Version 2.0.0
# File:    /root/.duplicity/backup-dirlist.sh
# Author:  Xavier Schoepfer
# license: GNU General Public License v3.0

/etc
/home
/usr/local
/var/lib/dpkg /var/log /var/mail
