# Duplicity backup configuration file



# S3 server config
S3_SERVER='S3ServerName'			# edit to configure
S3_PORT='443'
BUCKET_NAME='BucketName'			# edit to configure
export AWS_ACCESS_KEY_ID='AccessKeyId'		# edit to configure
export AWS_SECRET_ACCESS_KEY='SecretAccessKey'	# edit to configure
TARGET_PATH="backups/$HOSTNAME"



# GnuPG config
ENC_KEY='GnuPGKeySig'				# edit to configure
SIG_KEY=$ENC_KEY
export PASSPHRASE='GnuPG passphrase'		# edit to configure
export SIGN_PASSPHRASE=$PASSPHRASE
