# Duplicity backup configuration file

# Duplicity backup script-shell
# Version 2.0.0
# "Full backup" only
# File:    /root/.duplicity/duplicity.conf
# Author:  Xavier Schoepfer
# license: GNU General Public License v3.0



# complete S3 Object Storage server URL
TARGET_URL="s3://$S3_SERVER:$S3_PORT/$BUCKET_NAME/$TARGET_PATH"


# backup mode: full | incr
DUP_MODE="full"
#DUP_MODE="incr"


# DON'T backup any '.cache' or 'tmp' directories
DUP_PARAM="--exclude **/.cache --exclude **/tmp"
# command to run the backup
DUP_EXEC="duplicity $DUP_MODE $DUP_PARAM --encrypt-key $ENC_KEY --sign-key $SIG_KEY "
# command to verify the backup
DUP_VERIF="duplicity verify --encrypt-key $ENC_KEY --sign-key $SIG_KEY "
# command to remove backups older than 8 weeks
DUP_CLEANUP="duplicity remove-older-than 8W "


# list of directories to backup (⚠️  use absolute paths!)
DIRS2BACKUP="/etc /home /usr/local /var/lib/dpkg /var/log /var/mail"	# edit to configure
# SOON, the list of directories to be backed up will be
# read from the '/root/.duplicity/backup-dirlist.conf' file.
